### ISSUE TITLE
OriginalName of gh.exe exclusive to Windows

### ISSUE THREAD

**Issue by DonPwrShellHunt** [dfinke/PSGitHubCLICrescendo#1]
"OriginalName": "gh" 
works on MacOS, but I have not tested it on Windows & Linux. I think it should work on all platforms.

Using gh as a example for how Crescendo works was perfect. I had both gh & Crescendo on my radar & this combined the two!

**Comment by dfinke** [comment]
Thanks! Worked on Windows. I'll setup up a GitHub Action to test this on all three OSes.
