### ISSUE TITLE
New-GHGist support available

### ISSUE THREAD

**Issue by DonPwrShellHunt** [dfinke/PSGitHubCLICrescendo#2]
I have a reasonably complete implementation of creating a gist in my fork of this repo (master branch).
[Link to my fork](https://github.com/DonPwrShellHunt/PSGitHubCLICrescendo)

```PowerShell
New-GHGist [-Description] <string> [-Path] <string[]> [-Public] [-Online] [<CommonParameters>]
```

Tested variations include positional parameter usage for Description and Path, multiple paths, globbed paths, and switches for Public and Online (show in browser). Pipeline input is not handled in this version.

Example of verbose output

```powershell
PS /Users/donhunt/scratch> New-GHGist -Description 'GlobJsonFiles' -Path *.json -Public -Online -Verbose
VERBOSE: gh
VERBOSE: gist
VERBOSE: create
VERBOSE: *.json
VERBOSE: --public
VERBOSE: --web
VERBOSE: --desc
VERBOSE: GlobJsonFiles
VERBOSE: Performing the operation "New-GHGist" on target "gh".
- Creating gist with multiple files
✓ Created gist login_template.json
Opening gist.github.com/a2525c1ad55e0537ad0a37b99b169b3e in your browser.
```

**Comment by dfinke** [comment]
That's great. Thanks Don. Do a PR. I have one test, it `compiles` the json into the `psm1` and checks what functions should be created. You could update that to include yours. I'm still thinking through how deep to test this, maybe mocks.
